name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Retrieve IP
        run: |
          IP_ADDRESS=$(curl -s https://api.ipify.org)
          echo "IP_ADDRESS=${IP_ADDRESS}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: sudo docker build --build-arg REACT_APP_API_IP=$IP_ADDRESS --build-arg REACT_APP_API_PORT=8081 -t ras-front-image .

      - name: Stop Docker Containers
        run: sudo docker stop ras-front || true

      - name: Remove Existing Docker Containers
        run: sudo docker rm ras-front || true

      - name: Run Docker Container
        run: sudo docker run --rm -e REACT_APP_API_IP=$IP_ADDRESS -e REACT_APP_API_PORT=8081  -d -p 3000:3000 --name ras-front ras-front-image
