name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: sudo docker build -t ras-front-image .

      - name: Stop Docker Containers
        run: sudo docker stop ras-front || true

      - name: Remove Existing Docker Containers
        run: sudo docker rm ras-front || true

      - name: Run Docker Container
        run: sudo docker run --rm -d -p 3000:3000 --name ras-front ras-front-image
